spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/booklib
    ?useUnicode=true
    &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
    password: Zabbil@3qew8Nbi1984
  jpa:
    hibernate:
      ddl-auto: update

someParameter:
  value: 5463